create table if not exists public.fare_reference (
  id bigint generated by default as identity primary key,
  operator text not null,
  transport_mode text not null,
  origin_station text not null,
  destination_station text not null,
  fare_type text not null default 'adult_cash',
  adult_fare numeric(6,2) not null check (adult_fare >= 0),
  source_url text not null,
  source_date date,
  updated_at timestamptz not null default now(),
  unique (operator, transport_mode, origin_station, destination_station, fare_type)
);

alter table public.fare_reference enable row level security;

drop policy if exists "Public fare reference read" on public.fare_reference;
create policy "Public fare reference read"
on public.fare_reference
for select
to anon, authenticated
using (true);

insert into public.fare_reference (operator, transport_mode, origin_station, destination_station, fare_type, adult_fare, source_url, source_date)
values
  ('Rapid KL', 'MRT', 'Muzium Negara', 'Bukit Bintang', 'adult_cash', 1.80, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'MRT', 'Bukit Bintang', 'Muzium Negara', 'adult_cash', 1.80, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'MRT', 'Pasar Seni', 'Bukit Bintang', 'adult_cash', 1.40, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'MRT', 'Bukit Bintang', 'Pasar Seni', 'adult_cash', 1.40, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'MRT', 'Pasar Seni', 'Kajang', 'adult_cash', 3.60, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'MRT', 'Kajang', 'Pasar Seni', 'adult_cash', 3.60, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'MRT', 'Bukit Bintang', 'Kajang', 'adult_cash', 3.20, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'MRT', 'Kajang', 'Bukit Bintang', 'adult_cash', 3.20, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'LRT', 'KL Sentral', 'Pasar Seni', 'adult_cash', 1.30, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'LRT', 'Pasar Seni', 'KL Sentral', 'adult_cash', 1.30, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'LRT', 'KL Sentral', 'Masjid Jamek', 'adult_cash', 1.60, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'LRT', 'Masjid Jamek', 'KL Sentral', 'adult_cash', 1.60, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'LRT', 'KL Sentral', 'Dang Wangi', 'adult_cash', 2.00, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'LRT', 'Dang Wangi', 'KL Sentral', 'adult_cash', 2.00, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'LRT', 'KL Sentral', 'KLCC', 'adult_cash', 2.40, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'LRT', 'KLCC', 'KL Sentral', 'adult_cash', 2.40, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'LRT', 'KL Sentral', 'Ampang Park', 'adult_cash', 2.60, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'LRT', 'Ampang Park', 'KL Sentral', 'adult_cash', 2.60, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'LRT', 'KL Sentral', 'Bangsar', 'adult_cash', 1.20, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'LRT', 'Bangsar', 'KL Sentral', 'adult_cash', 1.20, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'LRT', 'KL Sentral', 'Abdullah Hukum', 'adult_cash', 1.50, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'LRT', 'Abdullah Hukum', 'KL Sentral', 'adult_cash', 1.50, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'LRT', 'KL Sentral', 'Universiti', 'adult_cash', 2.00, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'LRT', 'Universiti', 'KL Sentral', 'adult_cash', 2.00, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'LRT', 'KL Sentral', 'Taman Jaya', 'adult_cash', 2.20, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'LRT', 'Taman Jaya', 'KL Sentral', 'adult_cash', 2.20, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'LRT', 'KL Sentral', 'Subang Jaya', 'adult_cash', 3.60, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('Rapid KL', 'LRT', 'Subang Jaya', 'KL Sentral', 'adult_cash', 3.60, 'https://myrapid.com.my/bus-train/rapid-kl/integrated-fare-table/', '2021-05-06'),
  ('KTMB', 'KTM', 'KL Sentral', 'Mid Valley', 'adult_cash', 1.60, 'https://online.ktmb.com.my/', null),
  ('KTMB', 'KTM', 'Mid Valley', 'KL Sentral', 'adult_cash', 1.60, 'https://online.ktmb.com.my/', null),
  ('KTMB', 'KTM', 'KL Sentral', 'Bandar Tasik Selatan', 'adult_cash', 2.40, 'https://online.ktmb.com.my/', null),
  ('KTMB', 'KTM', 'Bandar Tasik Selatan', 'KL Sentral', 'adult_cash', 2.40, 'https://online.ktmb.com.my/', null),
  ('KTMB', 'KTM', 'KL Sentral', 'Serdang', 'adult_cash', 2.90, 'https://online.ktmb.com.my/', null),
  ('KTMB', 'KTM', 'Serdang', 'KL Sentral', 'adult_cash', 2.90, 'https://online.ktmb.com.my/', null),
  ('KTMB', 'KTM', 'KL Sentral', 'Kajang', 'adult_cash', 4.20, 'https://online.ktmb.com.my/', null),
  ('KTMB', 'KTM', 'Kajang', 'KL Sentral', 'adult_cash', 4.20, 'https://online.ktmb.com.my/', null),
  ('KTMB', 'KTM', 'KL Sentral', 'Batu Caves', 'adult_cash', 2.60, 'https://online.ktmb.com.my/', null),
  ('KTMB', 'KTM', 'Batu Caves', 'KL Sentral', 'adult_cash', 2.60, 'https://online.ktmb.com.my/', null)
on conflict (operator, transport_mode, origin_station, destination_station, fare_type)
do update set
  adult_fare = excluded.adult_fare,
  source_url = excluded.source_url,
  source_date = excluded.source_date,
  updated_at = now();